### ISSUE TITLE
Supermetrics 2.0 connector improvement

### ISSUE THREAD

**Issue by fdelgadodyvenia** [dyvenia/viadot#1023]
[src/viadot/sources/supermetrics.py](https://github.com/dyvenia/viadot/pull/1014/files/2a6a0fe9743c2405835bdf5b0ef0a41cad555445#diff-e50e80907fc248a1b70718c18a498ccb91aaeec535123f4d27dbebe040990203)
1) Source.to_json()
https://github.com/dyvenia/viadot/pull/1014#discussion_r1732803592

2) API Calls:
https://github.com/dyvenia/viadot/pull/1014#discussion_r1732815976

**Comment by trymzet** [comment]
@fdelgadodyvenia you can just link comments; updated that for you
