### ISSUE TITLE
`to_df` method is inheritted from base Source class and do not take additional parameters 

### ISSUE THREAD

**Issue by adrian-wojcik** [dyvenia/viadot#1052]
HI,

I faced that issue when migrating Eurostat Source. `to_df` method is taking only self and if_empty parameters, so there is no possibility to pass directly to to_df method more arguments (I tried and I had error that to many arguments are passed to the function). Maybe I did something wrong or something changed in base Source class. I see that most of the connectors have only 2 parameters, but for example sharepoint has multiple one and it seems that it does not inherited this method from base Source class.

**Comment by trymzet** [comment]
@adrian-wojcik that's not an issue with the library, you might need to learn OOP though to understand how inheritance works. Here's a working example of overriding the `to_df()` method:

```python
from viadot.sources.base import Source

class MySource(Source):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def to_df(self, x, y, z):
        print(x)
        print(y)
        print(z)

MySource().to_df(1, 2, 3)
```
