### ISSUE TITLE
Figure out how to handle config/credentials

### ISSUE THREAD

**Issue by Trymzet** [dyvenia/viadot#15]
Currently they're mixed together in `credentials.json` file. However, secret parameters (eg. the `credentials` parameter of many of our tasks) should be treated as Prefect Secrets and used inside the tasks with eg. `Secret(supermetrics_secret).get()`, where `supermetrics_secret` is the key in the key vault, eg. `supermetrics_secret = "my_supermetrics_creds"`. We should subclass `prefect.tasks.prefect.Secret` to use the secrets properly in Prefect (eg. use Azure Key Vault).

As for config, it's public, so it can be read from both a local file and env variables.

See [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/aws/secrets_manager.py) and [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/azure/blobstorage.py) for examples of subclassing and using the `Secret` class.

**Comment by acivitillo** [comment]
So fetching a secret becomes a task? How does this look like in the end user workflow? They create this task as one of the first tasks, return a dict, and use that dict going forward?

I guess I am not understanding the new `Secrete()` class behavior you are proposing. prefect's `SecretBase()` inherits from `Task()`.

**Comment by Trymzet** [comment]
Yes, you got that right. The user only passes they name of the secret to be used, eg `credentials_secret="supermetrics_credentials"`. 
This is eg. used with the built-in `Storage` classes:
```python
STORAGE = GitHub(
    repo="dyvenia/fiotto",
    path="fiotto/examples/hello_world.py",
    access_token_secret="github_token",  # name of the Prefect secret with the GitHub token
)
```
Creating secrets is done in the credentials manager of choice.

The `Sectret` task is a special kind of `Task` that's secure as it's not spilling/persisting data in the same way as standard tasks.

**Comment by Trymzet** [comment]
Added `ReadAzureKeyVaultSecret` Secret task that will allow us to implement the `KeyVault` credential storage.

**Comment by Trymzet** [comment]
This is done regarding tasks; as for implementing this for bare viadot (non-prefect parts), this is out of scope for now.
