### ISSUE TITLE
[admin] organize issues as project

### ISSUE THREAD

**Issue by vperluzzo** [dyvenia/viadot#16]
hi @acivitillo and @Trymzet 

I think this repo is running a bit wild and we should organize it a bit
happy to help but I'd need a collaborator access (right now all I can do is create issues)
for what I see you need 

- [x] Project creation
- [x] Simple kanban
- [ ] Proper labeling and issue assignment

now that I have a laptop that can use viadot would love to help even if it's just on improving docs from the new user perspective

**Comment by Trymzet** [comment]
I don't think it's really needed here for now with the small amount of issues.
