### ISSUE TITLE
Simplify the release process

### ISSUE THREAD

**Issue by trymzet** [dyvenia/viadot#168]
We've already simplified it by dropping the use of release branches and only using a single `dev` branch. The next step is to fully migrate to using the `GitHub` flow, ie. only the `main` branch (plus ad-hoc feature branches that make PRs to `main`):

![new_git_flow](https://user-images.githubusercontent.com/23084949/136548781-6663658d-7016-4063-a846-32611f5a59ca.PNG)

**Comment by Trymzet** [comment]
Moved to a single `dev` branch so far. Will move to the `GitHub` flow within the next few weeks.

**Comment by Trymzet** [comment]
Check out https://github.com/airbytehq/airbyte/blob/master/.github/workflows/release-airbyte-os.yml for a good release automation process
