### ISSUE TITLE
Improve `ADLSToAzureSQL` flow to support parquet files

### ISSUE THREAD

**Issue by Pmarek12** [dyvenia/viadot#169]
Hi @Nadiath-Waidi,

right now `ADLSToAzureSQL` flow supports only csv files. We need to improve this flow or create a separate one to be able to use parquet files from DL Gen2.

**Comment by Trymzet** [comment]
This would require using `AzureSQLBulkInsert` instead of `BCPTask`

**Comment by Trymzet** [comment]
Marked as `good first issue` as the likely solution is already sketched in detail (depending on point 1. of the TODO), so not much knowledge of `viadot` is required. However, it may require intermediate Python skills to finish.

**Comment by Trymzet** [comment]
This is not supported by Azure SQL. The solution is somewhat outside the box: it's to not use Azure SQL at all, but an SQL engine running on top of the lake, eg. Databricks SQL.
