### ISSUE TITLE
Move `df_map_mixed_dtypes_for_parquet_task` from `SharepointToADLS` to `task_utils`

### ISSUE THREAD

**Issue by Trymzet** [dyvenia/viadot#193]
This function should be generalized and defined in `task_utils` and then used in `SupermetricsToADLS` and `SharepointToADLS`.

**Comment by Rafalz13** [comment]
Function is generalized and used in ```SupermetricsToADLS ``` and ```SharepointToADLS```. Test for this function to added in test_task_utils.py
