### ISSUE TITLE
CloudForCustomersReportToADLS append doesn't work

### ISSUE THREAD

**Issue by Pmarek12** [dyvenia/viadot#209]
Hi @m-paz, @AdamSulek,

I have noticed that if we append data to .csv using CloudForCustomersReportToADLS flow, title columns are getting duplicated (horizontally)
![image](https://user-images.githubusercontent.com/48840222/143605725-54483882-4bc4-4def-9893-47f5361fdfb2.png)

**Comment by AdamSulek** [comment]
- [ ] solved column duplication in "append" mode by adding sep parameter in read_csv

**Comment by AdamSulek** [comment]
Here is PR for this issue: https://github.com/dyvenia/viadot/pull/220
