### ISSUE TITLE
ADLStoAzureSQL support unordered columns

### ISSUE THREAD

**Issue by Pmarek12** [dyvenia/viadot#213]
Hi @Trymzet, @m-paz, 
I have noticed that in order to use ADLStoAzureSQL flow, column list in the `csv` needs to be in the same order as declared in dtypes.

I think it will be good to create auto-mapping for columns, so we won't depend on the order. It is important, because we are pulling data from various sources and if someone will make changes in their infrastructure, we can get different `csv` (different order of the columns). Then we won't even get an error and we will keep loading data into wrong columns

It's an enhancement, rather than bug. I just wanted to point that behaviour 😃

**Comment by Trymzet** [comment]
I think this is a bug because providing dtypes shouldn't change the column order of the file.

**Comment by m-paz** [comment]
fix planned for next release

**Comment by Pmarek12** [comment]
@m-paz To better describe the problem I will show it on example.

We have csv:

![image](https://user-images.githubusercontent.com/48840222/146208225-e3285748-9f5f-4211-a00a-f5e943f3c068.png)


Then in code we have different order of columns, for example let [Ticket Type Text] be our first column:

![image](https://user-images.githubusercontent.com/48840222/146207433-ea898aee-848e-4710-9539-9159e2b99910.png)

As you can see table has the same order of columns as in code, [Ticket Type Text] is the first one:

![image](https://user-images.githubusercontent.com/48840222/146207721-bfddc1fe-6dc5-4498-bbdd-f8673c306340.png)

The problem is when you select data from that table:

![image](https://user-images.githubusercontent.com/48840222/146208499-fb7a5e2e-bb2e-4e60-a1b1-dbd1fae88533.png)

Under [Ticket Type Text] we have the same data as under [Incident Category ID] in csv.
The [Ticket Type Text] content in csv is:

![image](https://user-images.githubusercontent.com/48840222/146208107-939b0611-17fd-4d62-aefc-24f38ba94041.png)

So our script is loading csv as it is, but keeps column headers as we have in code which cause mismatches. Hope this help 🚀

**Comment by m-paz** [comment]
Covered in 0.3.2 release
