### ISSUE TITLE
Add more layers of flows for Pipeline

### ISSUE THREAD

**Issue by lzuchowska** [dyvenia/viadot#250]
The current state of flow_of_flows allows for two layers - extracts and transforms.
While adding extracts and transforms is widening the graph, we would like to have a functionality that allows for another layer, making the length bigger.

Current version looks like this:

![current](https://user-images.githubusercontent.com/91731298/149932834-39fd559a-7342-45a8-aeb9-7193a72c5410.png)

What we need:

![required](https://user-images.githubusercontent.com/91731298/149933088-b7fbc997-e421-4923-ac32-3560cd0a3567.png)

**Comment by Trymzet** [comment]
What's the new layer? There is no other step in ELT than these two.

**Comment by Trymzet** [comment]
don't we already have a flow for thart? CopyADLStoADLS or sth like that?

**Comment by lzuchowska** [comment]
Correct me if I'm wrong, but all I found was:

To ADLS:
- CloudForCustomersReportToADLS 
- SharepointToADLS 
- SupermetricsToADLS 
- CloudForCustomersToADLS 

ADLS to:
- ADLSToAzureSQL
