### ISSUE TITLE
[tasklib] run SQL code in SQLite

### ISSUE THREAD

**Issue by acivitillo** [dyvenia/viadot#29]
Create a standard task to run SQL code from a file on a SQLite db. 

## How the task should work

```python
from viadot.tasks.sqlite import RunSQL

task = RunSQL(path="/path/to/sql/file.sql")
df = task.run() #<- run returns a pandas df with results from sql query run
```

## Make sure you do the following before sending the PR:

- [x] Create a test case
- [x] Create a task in /tasks
- [x] Create documentation in `references` and `howtos`

## Help:

* sqlite tests: https://github.com/dyvenia/viadot/blob/main/tests/integration/test_sqlite.py

**Comment by Trymzet** [comment]
@AdamSulek pls close once you confirm all `sqlite` tests pass on 0.1.12

**Comment by Trymzet** [comment]
Finalized with 43fa294559222bcf829d5da870ffdb4c35d3da58
