### ISSUE TITLE
`ADLSToAzureSQL` appending to non-existent SQL table. 

### ISSUE THREAD

**Issue by bartek-plonkowski** [dyvenia/viadot#325]
Hi guys I noticed something while working with ADLSToAzureSQL flow.
We were loading data from gen2 to SQL table, and set the flow to append the table if it exists.
We assumed that it doesn't change anything in case if the table we want to append or create doesn't exist.
But when we wanted to append the table we got error message: " Detected discrepancies in number of columns or different column names between the CSV file and the SQL table!" which make us think that the problem is in columns.

Is it possible to make the flow ignore the fact that non-existent table can't be appended and create new if it doesn't exist?
If no, is it possible to add error code that would inform that the table we are trying append to doesn't exist?

Seems to be linked to previous issue raised by Piotrek Marek #145 

Pozdrawiam

**Comment by Trymzet** [comment]
@angelika233
