### ISSUE TITLE
Add handling of response code 503 (service unavailable) to `utils.handle_api_response()`

### ISSUE THREAD

**Issue by trymzet** [dyvenia/viadot#405]
This should handle 503 with a more graceful message:
```python
except Exception as e:
        raise APIError("Unknown error.") from e
```

**Comment by Trymzet** [comment]
On it

**Comment by Trymzet** [comment]
@angelika233 didn't you solve this already by any chance? :P

**Comment by angelika233** [comment]
> @angelika233 didn't you solve this already by any chance? :P

not yet 😄
