### ISSUE TITLE
Start publishing docs again?

### ISSUE THREAD

**Issue by trymzet** [dyvenia/viadot#440]
Seems like many people struggle to understand viadot and how it plays with the orchestration layer. Would be useful to start working on docs as we go & re-add a job the the CI/CD action to publish the docs on release.

Docs need updating, eg. adding new sources to https://github.com/dyvenia/viadot/blob/main/docs/references/sql_sources.md. Updating docs relevant to the PR should probably be part of the PR template checklist.

**Comment by trymzet** [comment]
@k-wolski are you able to publish docs to `.docs.dyvenia.com` from a branch? Because on this repo, we'd like the docs to come from the `2.0` branch.

**Comment by k-wolski** [comment]
sure, it's not a problem. So viadot.docs.dyvenia.com could be connected to `2.0` branch. Example that is pointing to `main`: https://github.com/dyvenia/mkdocs-nginx/blob/main/helm_values/dyvenia-internal-prod/nesso-cli/values.yaml#L9

**Comment by k-wolski** [comment]
Current issue:
```
ERROR   -  mkdocstrings: With sys.path = ['/tmp/github_repos/viadot', '/usr/local/bin', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/mkdocs/.local/lib/python3.9/site-packages',
           '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages'], accessing 'viadot' raises ModuleNotFoundError: No module named 'viadot'
ERROR   -  Error reading page 'references/api_sources.md':
ERROR   -  Could not collect 'viadot.sources.uk_carbon_intensity.UKCarbonIntensity'
```
@trymzet, please let me know here once it is added.

**Comment by k-wolski** [comment]
Thank you, it's working fine now. @djagoda881 please let me know once it will be merged somewhere in more stable branch. Right now I'm using `mkdocs-2.0-new_repo_structure`

**Comment by trymzet** [comment]
@k-wolski pls just use 2.0, it's already there and that is the target branch
