### ISSUE TITLE
fix reference documentation class docstring

### ISSUE THREAD

**Issue by acivitillo** [dyvenia/viadot#5]
@Trymzet can you check this out? I think you might be able to do this quickly. I would like the class docstring to show parameters as we can see for functions.

**Comment by Trymzet** [comment]
Done. Each new task needs to specify the class and task run docstrings:
```python
class MyTask(Task):
    """
    Class docs here
    """
    def run(self, some_arg):
        """
        Task run docs here
        """
        pass
```

1. Class init params:

![image](https://user-images.githubusercontent.com/23084949/124613572-a96c8980-de73-11eb-9e50-d724aa20d1dd.png)
2. Class docs:

![image](https://user-images.githubusercontent.com/23084949/124614616-b5a51680-de74-11eb-8049-a9395f8f08e1.png)
3. Task run docs:

![image](https://user-images.githubusercontent.com/23084949/124613691-c99c4880-de73-11eb-8631-582ac57d5d13.png)
