### ISSUE TITLE
Include partition option for to_parquet() and from_parquet() in S3 Source

### ISSUE THREAD

**Issue by TillPickha** [dyvenia/viadot#609]
Add additional parameters to both methods mentioned in title. This parameter should allow the user to apply partitioning when getting/sending data from S3.

**Comment by trymzet** [comment]
Doesn't seem like it's required anymore. If needed, see how the viadot 2.0 `MinIO` source uses `pyarrow.parquet` to support partitioning and multipart upload to S3.
