### ISSUE TITLE
`Circular import` when importing `credentials_loader` task

### ISSUE THREAD

**Issue by Rafalz13** [dyvenia/viadot#648]
There is a problem with circular import when credetials_loader is imported in this way -> `from viadot.task_utils import credentials_loader`. 
Fix for now -> `from viadot.task_utils import *` but this solution is not perfect.

```ImportError: cannot import name '[name]' from partially initialized module '[name]' (most likely due to a circular import) ([path_to_file].py)```

**Comment by trymzet** [comment]
I don't think there's such a thing as a "credentials_loader" in 2.0, so this can probably be closed?
