### ISSUE TITLE
dbt test failure handling in `TransformAndCatalog`

### ISSUE THREAD

**Issue by trymzet** [dyvenia/viadot#748]
`dbt test` step failing should not prevent the flow from sending metadata to Luma

It's up for discussion whether the flow itself should show as failed or successful -- probably failed, so as to send a notification?

These functionalities can be accomplished using [triggers](https://docs-legacy.prefect.io/api/0.6.7/triggers.html) (to run luma task despite the upstream dbt task failing) and [reference tasks](https://docs-legacy.prefect.io/api/0.8.1/core/flow.html#flow-2) (in case we want the flow to succeed despite a task failing).

**Comment by Rafalz13** [comment]
It's done and merged into the `main` branch. #750
