### ISSUE TITLE
Implement slack_handler notification logic inside viadot2

### ISSUE THREAD

**Issue by burzekj** [dyvenia/viadot#755]
- [x] the issue title describes briefly and clearly the **user story**
- [ ] the project is added
- [ ] the milestone is added, use **backlog** if you don't know the release yet
- [ ] you will write a list of **tasks** (like this list) to be closed for this user story

## Context
We need to implement additional logic inside viadot2.0 for future flow error handling with sending the notification on slack channels (with flow error message).  
The logic is described below:
https://docs.prefect.io/2.13.4/api-ref/prefect/blocks/notifications/
https://discourse.prefect.io/t/send-an-alert-when-a-flow-fails-with-a-decorator/1828/1

contact person for further questions:
@m-paz

**Comment by Trymzet** [comment]
This belongs to https://github.com/dyvenia/prefect-viadot, pls move the issue there.

Also, we already discussed the logic with @Rafalz13 for the `TransformAndCatalogToLuma` flow, pls align with him first and maybe split this user story into tasks, or at least define the tasks here as checkboxes?
