### ISSUE TITLE
Issue with bug related to query execution for class: AzureSQL

### ISSUE THREAD

**Issue by burzekj** [dyvenia/viadot#756]
- [x] the issue title describes briefly and clearly the **user story**
- [ ] the project is added
- [ ] the milestone is added, use **backlog** if you don't know the release yet
- [ ] you will write a list of **tasks** (like this list) to be closed for this user story

## Context
While query has 2 parts, first part correct and the second one with incorrect syntax we get succeed flow state with no action in database. We need to track the response from the database and catch error if the query didn't affect on database.

Flow logic:
```
from viadot.sources import AzureSQL
from viadot.tasks.azure_sql import get_credentials

credentials = get_credentials(credentials_secret="azuwevelcesql-p-001", vault_name = None)
a = AzureSQL(credentials=credentials)

result = a.run(query="""
select count(*) from raw.sap_sales_orders_quotations_cee;
insert into sandbox.kuba_test select top 10 * from raw.sap_sales_orders_quotations_cee;
""")
```

```
from viadot.flows import AzureSQLTransform

flow = AzureSQLTransform(
    name="2-conformed Quality afvc",
    query="""
        select count(*) from raw.sap_sales_orders_quotations_cee;
        insert into sandbox.kuba_test select top 10 * from raw.sap_sales_orders_quotations_cee;
    """,
    sqldb_credentials_secret="azuwevelcesql-p-001",
)
```
output:
```
[2023-10-03 07:54:49+0000] INFO - prefect.FlowRunner | Beginning Flow run for '2-conformed Quality afvc'
[2023-10-03 07:54:49+0000] INFO - prefect.TaskRunner | Task 'azure_sql_db_query': Starting task run...
[2023-10-03 07:54:51+0000] INFO - prefect.azure_sql_db_query | Successfully ran the query.
[2023-10-03 07:54:51+0000] INFO - prefect.TaskRunner | Task 'azure_sql_db_query': Finished task run for task with final state: 'Success'
[2023-10-03 07:54:51+0000] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
<Success: "All reference tasks succeeded.">
```
output from database:
<img width="145" alt="image" src="https://github.com/dyvenia/viadot/assets/125436423/68d03391-84cb-4dfd-bf28-80db9c1dd1af">

Possible solution:
We can add to /viadot/viadot/sources/base.py SQL class on run() func.
`cursor.rowcount`
rowcount method returns number of rows that query affect, with returned 0 rows affected we can rise un exception.

contact person for further questions:
@m-paz

**Comment by Trymzet** [comment]
This is viadot 1 so I'll unassign myself if that's ok?

**Comment by trymzet** [comment]
@burzekj This is a limitation of the underlying `pyodbc` library - you cannot execute multiple statements within a single `cursor.execute()` call. So yous, you'd have to modify the `Source.run()` method to work around this. Anyway I'm not sure it's a good idea to combine queries with DML statements in the first place - you should probably separate data ingestion from transformation.
