### ISSUE TITLE
T&C flows that contain models that depend on other tables don't materialize tables

### ISSUE THREAD

**Issue by hectorfa17** [dyvenia/viadot#802]
After running the affected table, we can observe that despite the fact that Prefect shows that the flow has run successfully, please check the [link](https://cloud.prefect.io/dyvenia/flow/0f1f8ae2-a5ec-40ea-869e-9b2a66e45d4a):

There's actually an error with the dbt_task_run. If we observe the dbt_task_run logs, we can see that the task cannot be completed because one of the tables is not created in dbt:

`('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name '<db_name>anonymizedtable'. (208) (SQLMoreResults)")`

We can confirm that in order to materialize the table of a model, all the tables the model needs to materialize the target table need to be already present in dbt, under the schema test_conformed or test_operational. 

We realized that in order to test the dbt models, it is more time-effective to create tables and test the results than testing with views because in most of the cases, even performing a SELECT TOP 10 * FROM in a view takes too much time (more than 10 min), please refer to this [issue](https://dev.azure.com/VELUX-IT-Dev/AIA/_workitems/edit/174681) we reported.

Due to the complexity of the Conformed and Operational models, running the flows in the right order to get all the tables without being impacted by the tables dependencies is proving quite challenging if done manually.

**Proposed solution:**

My idea to solve this issue is to schedule the flows following the same order or time we've got in Data Flows, keep them refreshing until we do the validation of everything and then we can unscheduled those and get rid of the tables.

**Comment by hectorfa17** [comment]
@Rafalz13 @adrian-wojcik

**Comment by hectorfa17** [comment]
Hey @Rafalz13 @adrian-wojcik  according to Mateusz Pazdior's comment, you will have to have a look at how to build tables on top of views.

**Comment by trymzet** [comment]
@hectorfa17 @adrian-wojcik @Rafalz13 is this still an issue?
