### ISSUE TITLE
Operational T&C Flows allocated in conformed/dbt path

### ISSUE THREAD

**Issue by hectorfa17** [dyvenia/viadot#804]
We have noticed that there are several flows that belong to Operational tables stored in the conformed/dbt path in data_flows instead of being stored in operational, please find the full list below:

flows/prod/conformed/dbt/c4c/dbt_cic_c4c_mail_all_interactions_global_to_luma.py
flows/prod/conformed/dbt/cic/dbt_cic_entries_volume_and_performance_to_luma.py
flows/prod/conformed/dbt/c4c/dbt_cic_c4c_daily_open_tickets_global_to_luma.py
flows/prod/conformed/dbt/cic/dbt_cic_customer_types_list_to_luma.py
flows/prod/conformed/dbt/cic/dbt_cic_mails_per_ticket_global_to_luma.py
flows/prod/conformed/dbt/cic/dbt_cic_inbound_calls_global_to_luma.py
flows/prod/conformed/dbt/cic/dbt_cic_mail_resolution_time_global_to_luma.py
flows/prod/conformed/dbt/cic/dbt_cic_mail_response_time_global_to_luma.py
flows/prod/conformed/dbt/aselite/dbt_cic_aselite_all_interactions_global_to_luma.py
flows/prod/conformed/dbt/cic/dbt_cic_mail_all_interactions_global_to_luma.py
flows/prod/conformed/dbt/aselite/dbt_cic_aselite_incoming_activities_volumes_to_luma.py
flows/prod/conformed/dbt/aselite/dbt_cic_aselite_outcoming_mail_volumes_to_luma.py
flows/prod/conformed/dbt/cisco/dbt_cic_cisco_inbound_global_operational_to_luma.py
flows/prod/conformed/dbt/mindful/dbt_cic_surveys_mindful_to_luma.py
flows/prod/conformed/dbt/outlook/dbt_cic_outlook_incoming_volumes_to_luma.py
flows/prod/conformed/dbt/c4c/dbt_cic_c4c_customer_type_to_luma.py
flows/prod/conformed/dbt/cic/dbt_cic_all_surveys_to_luma.py
flows/prod/conformed/dbt/cic/dbt_cic_global_active_resource_to_luma.py
flows/prod/conformed/dbt/genesys/dbt_cic_genesys_inbound_global_to_luma.py
flows/prod/conformed/dbt/outlook/dbt_cic_outlook_outcoming_volumes_to_luma.py

Is this intended? If not we will need to change the location of these flows to the right one.

Thanks for your time.

**Comment by hectorfa17** [comment]
@adrian-wojcik @Rafalz13

**Comment by adrian-wojcik** [comment]
All paths changed to operational
