### ISSUE TITLE
Fix api url in vidclub connector

### ISSUE THREAD

**Issue by KaterynaIurieva** [dyvenia/viadot#821]
Url for api endpoint should be changed, because parameters for endpoints got changed and value 'all' for parameter 'region' is no longer valid. Instead by default parameter 'region' shouldn't be used at all.

**Comment by Rafalz13** [comment]
It's done here: #822 . @KaterynaIurieva please confirm if it's fixed now.

**Comment by KaterynaIurieva** [comment]
> It's done here: #822 . @KaterynaIurieva please confirm if it's fixed now.

Yes, I will close an issue
