### ISSUE TITLE
OPTION (MAXRECURSION) bug when running flow remotely

### ISSUE THREAD

**Issue by BartoszKalka** [dyvenia/viadot#854]
## CONTEXT
When trying to run the flow the `MAXRECURSION` option added by nesso team seems not to work.
It works locally but the flow gives an error. When running locally on prod target  - `MAXRECURSION` option is working. 

Looks like there is a problem with the flow code, which doesn't take into account the newest requirement update.

**Comment by adrian-wojcik** [comment]
Changes implemented after testing in local environment. PR #855

**Comment by trymzet** [comment]
@adrian-wojcik @djagoda881 PR was merged so I assume this can be closed. In the future, remember to link the PR to the issue (by typing "Closes #issue-number" in the PR description) so that closing the PR automatically closes the issue.
