### ISSUE TITLE
Improve dependency management

### ISSUE THREAD

**Issue by djagoda881** [dyvenia/viadot#873]
Currently, we manage dependencies in the project through files like `requirements.txt`, `requirements-dev.txt`, and `setup.py`. The number of packages required for installation is increasing, causing issues in maintaining/updating dependencies in the project. The aim of this statement is to tentatively base the project's dependencies on the `pyproject.toml` file and utilize the [rye](https://rye-up.com/) package to streamline administration. In the tasks below, we can add a list of changes worth implementing.

- [x] Add the `pyproject.toml` file
- [x] Add ruff settings in `pyproject.toml` for static code analysis (and add ruff to VScode settings -- see eg. the [VSCode](https://github.com/dyvenia/nesso/blob/main/.vscode/settings.json) and [pyproject.toml](https://github.com/dyvenia/nesso/blob/main/pyproject.toml) configs in nesso)
- [x] Change packages installation in Dockerfile
- [x] Change packages installation in github actions
- [x] https://github.com/dyvenia/viadot/issues/604

**Comment by djagoda881** [comment]
@trymzet
Do you see any more tasks to add?

**Comment by trymzet** [comment]
@djagoda881 updated the top comment with more info
