### ISSUE TITLE
Upload data from CSV located into a personal computer to Azure DB

### ISSUE THREAD

**Issue by fdelgadodyvenia** [dyvenia/viadot#895]
When I use the class BCPTask(ShellTask), issues arise when the CSV employs commas as separators, leading to two main problems:

The error message is unclear; it fails to specify that the problem is related to the separator.
Why is the comma separator not accepted?"

**Comment by Rafalz13** [comment]
@fdelgadodyvenia Could you add some example of use or screenshot what error is generated?

**Comment by trymzet** [comment]
Closing as stale
