### ISSUE TITLE
Connector Migration: Genesys

### ISSUE THREAD

**Issue by fdelgadodyvenia** [dyvenia/viadot#903]
Implement the connector according to the data requirements localed here
https://docs.google.com/document/d/1DMY31YAzV5k0SYI6tMptEuTFqMwNF5c4uchsYkb8voY/edit

 - [x] Create the source (logic of the connectors)
 - [x] Create tasks and flow (wrappers of the main function in source)
 - [x] Create PR (@fdelgadodyvenia  reviewer)

**Comment by Diego-H-S** [comment]
PR: https://github.com/dyvenia/viadot/pull/934

**Comment by fdelgadodyvenia** [comment]
Migrated to 2.0-new-structrue branch
