### ISSUE TITLE
Connector Migration: Mediatool

### ISSUE THREAD

**Issue by fdelgadodyvenia** [dyvenia/viadot#906]
Implement the connector according to the data requirements localed here
https://docs.google.com/document/d/1DMY31YAzV5k0SYI6tMptEuTFqMwNF5c4uchsYkb8voY/edit

- [ ] Create the source (logic of the connectors)
- [ ] Create tasks and flow (wrappers of the main function in source)
- [ ] Create PR (@fdelgadodyvenia  reviewer)

**Comment by Diego-H-S** [comment]
PR: https://github.com/dyvenia/viadot/pull/963

**Comment by fdelgadodyvenia** [comment]
https://github.com/dyvenia/viadot/pull/963

**Comment by fdelgadodyvenia** [comment]
Stop PRs till 2.0 merged

**Comment by Diego-H-S** [comment]
New PR: https://github.com/dyvenia/viadot/pull/1038
