### ISSUE TITLE
Connector Migration: SFTP

### ISSUE THREAD

**Issue by fdelgadodyvenia** [dyvenia/viadot#908]
Implement the connector according to the data requirements localed here
https://docs.google.com/document/d/1DMY31YAzV5k0SYI6tMptEuTFqMwNF5c4uchsYkb8voY/edit

 - [ ] Create the source (logic of the connectors)
 - [ ] Create tasks and flow (wrappers of the main function in source)
 - [ ] Create PR (@fdelgadodyvenia  reviewer)

**Comment by Diego-H-S** [comment]
PR: https://github.com/dyvenia/viadot/pull/1039
