### ISSUE TITLE
the docker jupyter lab container doesn't work

### ISSUE THREAD

**Issue by acivitillo** [dyvenia/viadot#91]
I have run `update.sh` and then `run.sh` and I get the following error for the jupyterlab container:

```bash
viadot_jupyter_lab    | /usr/local/bin/entrypoint.sh: line 24: exec: jupyter: not found
```

It's behaving as if there was no jupyter installed in the `viadot:dev` image

**Comment by Trymzet** [comment]
To get the `dev` image, you need to run `update.sh -t dev`. Can you try that one? I just updated mine and I don't see any problems. 

I'll make a release in the next 2-3 days so that the latest image is also fixed.

**Comment by Trymzet** [comment]
I remember now we had an issue because MSSQL driver got a new release and we had a hardcoded one in `odbcinst.ini`. I fixed that now with https://github.com/dyvenia/viadot/commit/a5b4ed9dde16b630f0bc357daf9f42d1ad4c1dfd. Will close once you confirm dev is working for you.
