### ISSUE TITLE
Connectors Migration: Check Pending PRs and Merge

### ISSUE THREAD

**Issue by fdelgadodyvenia** [dyvenia/viadot#910]
- [x] big_query
- [x] sales_force
- [x] supermetrics
- [x] pass code checker
- [x] create unit tests
- [x] create integration tests

Create a PR for each source!

**Comment by fdelgadodyvenia** [comment]
[sales_force.txt](https://github.com/user-attachments/files/16391910/sales_force.txt)
[test_salesforce.txt](https://github.com/user-attachments/files/16391909/test_salesforce.txt)



[supermetrics.txt](https://github.com/user-attachments/files/16391915/supermetrics.txt)
[test_integration_supermetrics.txt](https://github.com/user-attachments/files/16391914/test_integration_supermetrics.txt)
[test_unit_supermetrics.txt](https://github.com/user-attachments/files/16391916/test_unit_supermetrics.txt)




[bigquery.txt](https://github.com/user-attachments/files/16391949/bigquery.txt)

[test_bigquery.txt](https://github.com/user-attachments/files/16391958/test_bigquery.txt)

**Comment by Diego-H-S** [comment]
BigQuery PR: https://github.com/dyvenia/viadot/pull/1035

**Comment by Diego-H-S** [comment]
Salesforce PR: https://github.com/dyvenia/viadot/pull/1036
