### ISSUE TITLE
`_get_aws_credentials()` should use the Prefect `AwsSecret` block rather than `awswrangler` lib

### ISSUE THREAD

**Issue by trymzet** [dyvenia/viadot#951]
The `_get_aws_credentials()` (https://github.com/dyvenia/viadot/blob/2.0-new-repository-structure/src/viadot/orchestration/prefect/utils.py#L56-L72) should read the block (same as `_get_azure_credentials()`) instead of using AWS wrangler lib.

Closing PR #989

**Comment by marcinpurtak** [comment]
Done but no PR created yet
